### ISSUE TITLE
Support for SPM (Swift Package Manager)

### ISSUE THREAD

**Issue by Rep0se** [freshworks/freshchat-ios#102]
As a lot of Swift developers are moving away from using CocoaPods towards SPM, can you add SPM support by providing Package.swift manifest file with the framework?
![Screen Shot 2020-05-12 at 10 57 26 AM](https://user-images.githubusercontent.com/34381835/81708794-7a10e700-943f-11ea-84f0-449f6166cbcf.png)

**Comment by ealeksandrov** [comment]
Freshchat SDK is supplied as a binary static lib, which is not supported by current versions of SPM/Xcode.

Binary dependencies support ([SE-0272](https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md)) is included into Swift 5.3 to be released in the future.

**Comment by saltyskip** [comment]
Any update on this

**Comment by iangmaia** [comment]
Now that Xcode 12 / Swift 5.3 has been released, this finally became feasible (and important for developers using the SDK)

**Comment by sandpat** [comment]
I tried creating an xcframework to share the binary via SPM but seems like the static library provided in the repo is an universal libary targeted for multiple platforms and one cannot create .xcframework file using this binary.
```zsh
xcodebuild -create-xcframework -library FreshchatSDK/libFDFreshchatSDK.a -headers FreshchatSDK/ -output output/FreshchatSDK.xcframework
```

`error: binaries with multiple platforms are not supported`

**Comment by idoNaveh** [comment]
Do you have an update on when the SPM support will be available?

**Comment by T2SoftDev** [comment]
@hemanth-sudarsan, @harish-kumarc
Could you please give us any comments about SPM support?

**Comment by hemanth-sudarsan** [comment]
We dont have any plans on SPM migration.

**Comment by T2SoftDev** [comment]
@hemanth-sudarsan

> We dont have any plans on SPM migration.

But why? Apple has done everything to support binary distribution of frameworks with SPM. Even Google has added SPM distribution for their large pack of complicated framewokrs - Firebase. Support for SPM becomes mainstream instead of Cocoapods/Carthage. And you don't have any plans?

So many projects trying to get rid of Cocoapods/Carthage to use SPM as native Apple technology fully integrated with Xcode. When all dependencies of your project are build with SPM and the only one dependency you have to check for updates & integrate manually is Freshchat - it raises questions...

Please reconsider your plans 🙏
