### ISSUE TITLE
Not able to set Navigation Title and icon color.

### ISSUE THREAD

**Issue by maheshsphinx** [freshworks/freshchat-ios#120]
I am using FreshchatSDK 3.4.0 pod version, 
Please see the attached image. I am not able to set white color to navigation title, search icon and Close button. But it doesn't work.
I have done with FCTheme.plist changes.
NavigationBar -> textColor -> #FFFFFF
ActionButtonStyle -> #FFFFFF
But changes are not reflected.
Please help me ASAP.
Thanks

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-16 at 17 51 08](https://user-images.githubusercontent.com/16081570/93336537-84a41880-f845-11ea-944f-8ed8df77bc54.png)

**Comment by harish-kumarc** [comment]
Hi @maheshsphinx ,
Please cleaning the build and run your project.

To change title colour user key highlighted below in FCTheme.plist
<img width="907" alt="Screenshot 2020-09-17 at 4 07 28 PM" src="https://user-images.githubusercontent.com/16202319/93459931-20925a80-f900-11ea-80de-60fd263b4e31.png">


For Close Button -
<img width="906" alt="Screenshot 2020-09-17 at 4 10 17 PM" src="https://user-images.githubusercontent.com/16202319/93460051-533c5300-f900-11ea-84ea-8225680a3338.png">


For navigation bar background color -
<img width="908" alt="Screenshot 2020-09-17 at 4 11 22 PM" src="https://user-images.githubusercontent.com/16202319/93460169-736c1200-f900-11ea-90f0-8c63abf0c290.png">

Also make sure that you are making changes into correct plist file.
Thanks, let us know if the issue is resolved.

**Comment by maheshsphinx** [comment]
@harish-kumarc Its working now!
